#!/bin/bash
set -e

# Parse arguments to select IaC provider (default: terraform)
USE_PULUMI=false
if [ "$1" == "--pulumi" ]; then
    USE_PULUMI=true
fi

if [ "$USE_PULUMI" = true ]; then
    echo "🌐 Step 1: Running Pulumi Up to provision cloud infrastructure..."
    cd ../pulumi
    export PULUMI_CONFIG_PASSPHRASE="SecurePass123!"
    ~/.pulumi/bin/pulumi up --yes
    
    echo "🔍 Extracting Pulumi outputs..."
    EC2_IP=$(~/.pulumi/bin/pulumi stack output ec2_public_ip)
    RDS_ENDPOINT=$(~/.pulumi/bin/pulumi stack output rds_endpoint)
    RDS_HOST=$(echo "$RDS_ENDPOINT" | cut -d':' -f1)
    cd ../app
else
    echo "🌐 Step 1: Running Terraform Apply to provision cloud infrastructure..."
    cd ../terraform
    terraform apply -auto-approve
    
    echo "🔍 Extracting Terraform outputs..."
    EC2_IP=$(terraform output -raw ec2_public_ip)
    RDS_ENDPOINT=$(terraform output -raw rds_endpoint)
    RDS_HOST=$(echo "$RDS_ENDPOINT" | cut -d':' -f1)
    cd ../app
fi

# Load passwords/users from .env if it exists, otherwise fall back to defaults
DB_USER="dbadmin"
DB_PASSWORD="SecurePass123!"
DB_NAME="postgres"

if [ -f .env ]; then
    # Safely extract passwords without exporting raw file string to subshells
    LOCAL_PASS=$(grep DB_PASSWORD .env | cut -d'=' -f2 | tr -d '"' | tr -d "'")
    if [ ! -z "$LOCAL_PASS" ]; then
        DB_PASSWORD="$LOCAL_PASS"
    fi
    LOCAL_USER=$(grep DB_USER .env | cut -d'=' -f2 | tr -d '"' | tr -d "'")
    if [ ! -z "$LOCAL_USER" ]; then
        DB_USER="$LOCAL_USER"
    fi
fi

# Re-write the local .env file with the newly generated IP and Host values
cat << EOF > .env
# AWS Deployment Variables (Auto-generated by deploy.sh)
EC2_IP="$EC2_IP"
RDS_HOST="$RDS_HOST"
DB_USER="$DB_USER"
DB_PASSWORD="$DB_PASSWORD"
DB_NAME="$DB_NAME"
EOF

# Validate resolved variables
if [ -z "$EC2_IP" ] || [ -z "$RDS_HOST" ]; then
    echo "ERROR: Failed to resolve EC2 IP or RDS Host from Terraform outputs."
    exit 1
fi

# Query AWS Account ID using CLI to dynamically construct ARNs and Buckets
echo "Querying AWS Account ID..."
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
if [ -z "$AWS_ACCOUNT_ID" ]; then
    echo "ERROR: Could not query AWS Account ID. Ensure 'aws configure' is complete."
    exit 1
fi

SNS_TOPIC_ARN="arn:aws:sns:eu-north-1:$AWS_ACCOUNT_ID:order-placed-topic"
S3_BUCKET="suleman-parcels-invoices-$AWS_ACCOUNT_ID"

echo "Using SNS Topic ARN: $SNS_TOPIC_ARN"
echo "Using S3 Bucket Name: $S3_BUCKET"

# SSH Key Resolution
if [ -f ~/.ssh/id_ed25519_github ]; then
    SSH_KEY="~/.ssh/id_ed25519_github"
elif [ -f ~/.ssh/gitlab_ed25519 ]; then
    SSH_KEY="~/.ssh/gitlab_ed25519"
else
    echo "ERROR: No valid SSH private key found in ~/.ssh/"
    exit 1
fi

echo "Using SSH Key: $SSH_KEY"
echo "Step 1: Building Spring Boot application locally..."
mvn clean package -DskipTests

echo "Step 2: Preparing Dockerfile on the fly..."
cat << 'EOF' > target/Dockerfile.run
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY app.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
EOF

echo "Step 3: Copying JAR and Dockerfile to EC2 server ($EC2_IP)..."
# Disable host key checking for ease of PoC connection
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no target/cloud-infra-poc-0.0.1-SNAPSHOT.jar ubuntu@"$EC2_IP":/home/ubuntu/app.jar
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no target/Dockerfile.run ubuntu@"$EC2_IP":/home/ubuntu/Dockerfile.run

ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no ubuntu@"$EC2_IP" << EOF
  # Wait for Docker to be fully installed by the EC2 boot script (user_data)
  echo "Waiting for Docker installation to complete on the EC2 instance..."
  for i in {1..30}; do
    if command -v docker &> /dev/null; then
      echo "Docker is ready!"
      break
    fi
    echo "Docker is still installing in the background... waiting 10 seconds (try \$i/30)"
    sleep 10
  done

  if ! command -v docker &> /dev/null; then
    echo "ERROR: Docker was not installed within 5 minutes."
    exit 1
  fi

  # Stop and remove the old container if it exists
  sudo docker stop spring-boot-app || true
  sudo docker rm spring-boot-app || true

  # Build the image on the EC2 instance
  sudo docker build -t cloud-infra-poc:latest -f Dockerfile.run .

  # Run the Spring Boot container, linking it to the RDS Database
  sudo docker run -d \
    --name spring-boot-app \
    -p 80:8080 \
    -e DB_HOST="$RDS_HOST" \
    -e DB_PORT=5432 \
    -e DB_NAME="$DB_NAME" \
    -e DB_USER="$DB_USER" \
    -e DB_PASSWORD="$DB_PASSWORD" \
    -e SNS_TOPIC_ARN="$SNS_TOPIC_ARN" \
    -e S3_BUCKET="$S3_BUCKET" \
    -e AWS_REGION="eu-north-1" \
    --restart always \
    cloud-infra-poc:latest
EOF

echo "🎉 Deployment completed successfully!"
echo "Check the health: http://$EC2_IP/api/orders/healthcheck"
